In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("seismic-bumps.csv")

In [3]:
data.head()

id seismic seismoacoustic shift  genergy  gpuls  gdenergy  gdpuls ghazard  \
0   1       a              a     N    15180     48       -72     -72       a   
1   2       a              a     N    14720     33       -70     -79       a   
2   3       a              a     N     8050     30       -81     -78       a   
3   4       a              a     N    28820    171       -23      40       a   
4   5       a              a     N    12640     57       -63     -52       a   

   nbumps  nbumps2  nbumps3  nbumps4  nbumps5  nbumps6  nbumps7  nbumps89  \
0       0        0        0        0        0        0        0         0   
1       1        0        1        0        0        0        0         0   
2       0        0        0        0        0        0        0         0   
3       1        0        1        0        0        0        0         0   
4       0        0        0        0        0        0        0         0   

   energy  maxenergy  class  
0       0          0      0  
1    2000       2000      0  
2       0          0      0  
3    3000       3000      0  
4       0          0      0

In [4]:
data.shape

(2584, 20)

In [5]:
data['class'].value_counts()

0    2414
1     170
Name: class, dtype: int64

In [6]:
data['seismic'].unique()

array(['a', 'b'], dtype=object)

In [7]:
data['seismic'].value_counts()

a    1682
b     902
Name: seismic, dtype: int64

In [8]:
data['seismoacoustic'].unique()

array(['a', 'b', 'c'], dtype=object)

In [9]:
data['seismoacoustic'].value_counts()

a    1580
b     956
c      48
Name: seismoacoustic, dtype: int64

In [10]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['seismic']= label_encoder.fit_transform(data['seismic']) 
  
data['seismic'].unique() 

array([0, 1], dtype=int64)

In [11]:
data['seismic']

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
2554    0
2555    0
2556    0
2557    0
2558    1
2559    1
2560    1
2561    1
2562    1
2563    1
2564    1
2565    1
2566    1
2567    1
2568    1
2569    1
2570    1
2571    1
2572    1
2573    1
2574    1
2575    1
2576    1
2577    1
2578    1
2579    1
2580    1
2581    1
2582    0
2583    0
Name: seismic, Length: 2584, dtype: int64

In [12]:

data['seismoacoustic']= label_encoder.fit_transform(data['seismoacoustic']) 
  
data['seismoacoustic'].unique() 

array([0, 1, 2], dtype=int64)

In [13]:

data['ghazard']= label_encoder.fit_transform(data['ghazard']) 
  
data['ghazard'].unique() 

array([0, 1, 2], dtype=int64)

In [14]:
data['shift']= label_encoder.fit_transform(data['shift']) 
  
data['shift'].unique() 

array([0, 1], dtype=int64)

In [15]:
data.head()

id  seismic  seismoacoustic  shift  genergy  gpuls  gdenergy  gdpuls  \
0   1        0               0      0    15180     48       -72     -72   
1   2        0               0      0    14720     33       -70     -79   
2   3        0               0      0     8050     30       -81     -78   
3   4        0               0      0    28820    171       -23      40   
4   5        0               0      0    12640     57       -63     -52   

   ghazard  nbumps  nbumps2  nbumps3  nbumps4  nbumps5  nbumps6  nbumps7  \
0        0       0        0        0        0        0        0        0   
1        0       1        0        1        0        0        0        0   
2        0       0        0        0        0        0        0        0   
3        0       1        0        1        0        0        0        0   
4        0       0        0        0        0        0        0        0   

   nbumps89  energy  maxenergy  class  
0         0       0          0      0  
1         0    2000       2000      0  
2         0       0          0      0  
3         0    3000       3000      0  
4         0       0          0      0

In [16]:
X = data.drop('class', axis = 1)
y= data['class']

In [17]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
data_Check = LogisticRegression()
data_Check.fit(X_train, y_train)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  93.03675048355899 %


In [20]:
y_train.value_counts()

0    1930
1     137
Name: class, dtype: int64

In [21]:
from imblearn.over_sampling import SMOTE
smt = SMOTE()
X_train1, y_train1 = smt.fit_sample(X_train, y_train)

In [22]:
np.bincount(y_train1)

array([1930, 1930], dtype=int64)

In [23]:
from sklearn.linear_model import LogisticRegression
data_Check = LogisticRegression()
data_Check.fit(X_train1, y_train1)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  73.88781431334623 %


In [24]:
from sklearn.ensemble import RandomForestClassifier
data_Check= RandomForestClassifier(random_state=1)
data_Check.fit(X_train1, y_train1)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

C:\Users\Uponika\Anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


accuracy =  93.42359767891682 %


In [25]:
from sklearn.ensemble import RandomForestClassifier
data_Check= RandomForestClassifier(random_state=1)
data_Check.fit(X_train, y_train)
y_pred = data_Check.predict(X_test)
correct = (y_pred == y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")

accuracy =  93.03675048355899 %


In [26]:
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_train1, y_train1) 
y_pred = data_classifier.predict(X_test)


correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")


accuracy =  88.39458413926499 %


In [27]:
from sklearn.tree import DecisionTreeClassifier  
data_classifier = DecisionTreeClassifier()  
data_classifier.fit(X_train, y_train) 
y_pred = data_classifier.predict(X_test)


correct = (y_pred==y_test).sum()
accuracy = correct/len(y_test)*100
print("accuracy = ", accuracy, "%")


accuracy =  89.55512572533848 %
